### ISSUE TITLE
Compiler rrrors when building for tizen 5.5

### ISSUE THREAD

**Issue by nscotto** [nnstreamer/nntrainer#855] opened 2021-01-15 15:47 UTC
I am trying to build nntrainer for tizen 5.5, the build process fails with some compiler errors:
```
 597 [   90s] [11/153] Compiling C++ object 'nntrainer/d48ed23@@nntrainer@sha/nnstreamer_layer.cpp.o'.
 598 [   90s] FAILED: nntrainer/d48ed23@@nntrainer@sha/nnstreamer_layer.cpp.o
 599 [   90s] c++ -Inntrainer/d48ed23@@nntrainer@sha -Inntrainer -I../nntrainer -Inntrainer/../api -I../nntrainer/../api -I../nntrainer/../api/ccapi/include -I/usr/include/nnstreamer -Inntra
 600 [   90s] In file included from /usr/include/nnstreamer/nnstreamer-single.h:29:0,
 601 [   90s]                  from ../nntrainer/layers/nnstreamer_layer.h:19,
 602 [   90s]                  from /home/abuild/rpmbuild/BUILD/nntrainer-0.1.1/nntrainer/layers/nnstreamer_layer.cpp:18:
 603 [   90s] /usr/include/nnstreamer/nnstreamer.h:165:35: error: redeclaration of 'tizen_error_e ML_ERROR_NONE'
 604 [   90s]    ML_ERROR_NONE                 = TIZEN_ERROR_NONE, /**< Success! */
 605 [   90s]                                    ^~~~~~~~~~~~~~~~
```

There are a lot more than this one, but it wouldn't fit on the page.
Any idea what could cause this failure?
I can share the full log if needed.

Thank you.

**Comment by zhoonit** [comment] 2021-01-18 07:05
Could you give us more information to reproduce the issue?

IMO, the commit id of the repo, build command and gbs conf should do.

**Comment by kparichay** [comment] 2021-01-18 08:46
@zhoonit I think the issue is that with tizen 5.5, nnstreamer includes error code (as `ml_error_e`) with `nnstreamer.h` header than a separate header. (`tizen_error.h` with tizen 6.0). This creates the error on redeclaration. Please let me know if you can check this on your side. IMO you can either add a patch to tizen_5.5 branch of nnstreamer to update the headers (make sure not to break existing applications) or check declarations on nntrainer side depending on tizen version.

@nscotto As nntrainer is official released since tizen 6.0, we did not test with nnstreamer in earlier versions of tizen (tizen 5.5 in this case). Based on the issue https://github.com/nnstreamer/nntrainer/issues/851, can you please describe the application and the architecture/os version you want to use nntrainer for? We will able to help you better with this.

**Comment by zhoonit** [comment] 2021-01-18 08:56
later should work, I'll make a patch

**Comment by zhoonit** [comment] 2021-01-20 08:07
Added a workaround patch under tizen 6. (#866) 
Please note that tizen_5.5 is not officially supported, although the patch should make it working as of now, it might not in the near future.

**Comment by kparichay** [comment] 2021-02-05 05:39
@nscotto Is this issue resolved?

**Comment by nscotto** [comment] 2021-02-24 14:32
Yes! Sorry for the late reply.

**Comment by zhoonit** [comment] 2021-02-25 02:04
Thank you for the reply :) I'll close this issue.

**Closed by zhoonit** 2021-02-25 02:04 UTC
